{
 "title": "NFT Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "NFT Projects",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT name, DATEDIFF(mint_date, now()) as \"days left\", twitter_link, blockchain, mint_price, count, max(twitter) as twitter, whitelist\r\nFROM all_projects, data\r\nWHERE all_projects.id = data.project_id\r\nGROUP BY name\r\norder by 2"
    }
   ]
  },
  {
   "title": "Twitter Follower",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  fetch_date AS \"time\",\r\n  twitter AS \"\",\r\n  name\r\nFROM data, all_projects\r\n\r\nWHERE all_projects.id = data.project_id \r\n"
    }
   ]
  },
  {
   "title": "Opensea Floor Prices",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  name,\r\n  date AS \"time\",\r\n  value as \"\"\r\nFROM floor_price_values\r\nORDER BY date"
    }
   ]
  },
  {
   "title": "Opensea Floor Prices",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT name, value\r\nFROM floor_price_values AS a\r\nWHERE date = (\r\n    SELECT MAX(date)\r\n    FROM floor_price_values AS b\r\n    WHERE a.name = b.name\r\n)"
    }
   ]
  }
 ]
}